version: '3.8'

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: uoft2025
      POSTGRES_USER: postgres
      POSTGRES_DB: codetierlist
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    restart: always
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - DB_HOST=db

volumes:
  db_data:
